version: "3.7"
services:
    php:
        image: php:8.1-fpm
        container_name: my-laravel-app-php
        volumes:
            - ./application:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel-net

    nginx:
        image: nginx:latest
        container_name: my-laravel-app-nginx
        ports:
            - "80:80"
        volumes:
            - ./application:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel-net

    postgres:
        image: postgres:latest
        container_name: my-laravel-app-postgres
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret_password
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - laravel-net

networks:
    laravel-net:

volumes:
    pg-data:
